// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package coordination

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CoordinationClient is the client API for Coordination service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoordinationClient interface {
	Request(ctx context.Context, in *ReqSetLeader, opts ...grpc.CallOption) (*ReplySetLeader, error)
	SetLeader(ctx context.Context, in *ReqSetLeader, opts ...grpc.CallOption) (*ReplySetLeader, error)
}

type coordinationClient struct {
	cc grpc.ClientConnInterface
}

func NewCoordinationClient(cc grpc.ClientConnInterface) CoordinationClient {
	return &coordinationClient{cc}
}

func (c *coordinationClient) Request(ctx context.Context, in *ReqSetLeader, opts ...grpc.CallOption) (*ReplySetLeader, error) {
	out := new(ReplySetLeader)
	err := c.cc.Invoke(ctx, "/coordination.Coordination/request", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationClient) SetLeader(ctx context.Context, in *ReqSetLeader, opts ...grpc.CallOption) (*ReplySetLeader, error) {
	out := new(ReplySetLeader)
	err := c.cc.Invoke(ctx, "/coordination.Coordination/setLeader", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoordinationServer is the server API for Coordination service.
// All implementations must embed UnimplementedCoordinationServer
// for forward compatibility
type CoordinationServer interface {
	Request(context.Context, *ReqSetLeader) (*ReplySetLeader, error)
	SetLeader(context.Context, *ReqSetLeader) (*ReplySetLeader, error)
	mustEmbedUnimplementedCoordinationServer()
}

// UnimplementedCoordinationServer must be embedded to have forward compatible implementations.
type UnimplementedCoordinationServer struct {
}

func (UnimplementedCoordinationServer) Request(context.Context, *ReqSetLeader) (*ReplySetLeader, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Request not implemented")
}
func (UnimplementedCoordinationServer) SetLeader(context.Context, *ReqSetLeader) (*ReplySetLeader, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLeader not implemented")
}
func (UnimplementedCoordinationServer) mustEmbedUnimplementedCoordinationServer() {}

// UnsafeCoordinationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoordinationServer will
// result in compilation errors.
type UnsafeCoordinationServer interface {
	mustEmbedUnimplementedCoordinationServer()
}

func RegisterCoordinationServer(s grpc.ServiceRegistrar, srv CoordinationServer) {
	s.RegisterService(&Coordination_ServiceDesc, srv)
}

func _Coordination_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqSetLeader)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coordination.Coordination/request",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationServer).Request(ctx, req.(*ReqSetLeader))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordination_SetLeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqSetLeader)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationServer).SetLeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coordination.Coordination/setLeader",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationServer).SetLeader(ctx, req.(*ReqSetLeader))
	}
	return interceptor(ctx, in, info, handler)
}

// Coordination_ServiceDesc is the grpc.ServiceDesc for Coordination service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Coordination_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coordination.Coordination",
	HandlerType: (*CoordinationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "request",
			Handler:    _Coordination_Request_Handler,
		},
		{
			MethodName: "setLeader",
			Handler:    _Coordination_SetLeader_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coordination/Coordination.proto",
}
