/*
 * ITU REST service 1.0
 *
 * Hello, World!
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Teacher struct {

	Id int64 `json:"id,omitempty"`

	Name string `json:"Name,omitempty"`
}
