/*
 * ITU REST service 1.0
 *
 * Hello, World!
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/api/v1/",
		Index,
	},

	Route{
		"CourseCourseIdDelete",
		strings.ToUpper("Delete"),
		"/api/v1/course/{courseId}",
		CourseCourseIdDelete,
	},

	Route{
		"CourseCourseIdGet",
		strings.ToUpper("Get"),
		"/api/v1/course/{courseId}",
		CourseCourseIdGet,
	},

	Route{
		"CoursePost",
		strings.ToUpper("Post"),
		"/api/v1/course",
		CoursePost,
	},

	Route{
		"AddStudent",
		strings.ToUpper("Post"),
		"/api/v1/student",
		AddStudent,
	},

	Route{
		"DeleteStudent",
		strings.ToUpper("Delete"),
		"/api/v1/student/{studentId}",
		DeleteStudent,
	},

	Route{
		"GetStudentById",
		strings.ToUpper("Get"),
		"/api/v1/student/{studentId}",
		GetStudentById,
	},

	Route{
		"UpdateStudent",
		strings.ToUpper("Put"),
		"/api/v1/student",
		UpdateStudent,
	},
}
